version: '3.9'
services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=house-helper-php
    ports:
      - '5342:5432'
